# Generated by Django 4.2.1 on 2023-05-13 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_delete_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('subtitle', models.CharField(max_length=60, verbose_name='Subtitle')),
                ('img', models.ImageField(upload_to='images', verbose_name='Background Image')),
            ],
        ),
    ]
