# Generated by Django 4.2.1 on 2023-05-13 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_hometitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='hometitle',
            name='class1',
            field=models.CharField(default=1, max_length=50, verbose_name='Classname'),
            preserve_default=False,
        ),
    ]
