# Generated by Django 4.2.1 on 2023-05-13 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_alter_product_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='datetime',
            field=models.DateField(auto_now=True, verbose_name='Datetime'),
        ),
    ]
