# Generated by Django 4.2.1 on 2023-05-13 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_alter_product_options_alter_product_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('subtitle1', models.CharField(max_length=50, verbose_name='Subtitle 1')),
                ('info1', models.CharField(max_length=100, verbose_name='Info 1')),
                ('info2', models.CharField(max_length=100, verbose_name='Info 2')),
                ('info3', models.CharField(max_length=100, verbose_name='Info 3')),
                ('info4', models.CharField(max_length=100, verbose_name='Info 4')),
                ('info5', models.CharField(max_length=100, verbose_name='Info 5')),
                ('btn_name1', models.CharField(max_length=40, verbose_name='Button Name 1')),
                ('img', models.ImageField(upload_to='images', verbose_name='Image')),
                ('subtitle2', models.CharField(max_length=50, verbose_name='Subtitle 2')),
                ('text2', models.TextField(verbose_name='Text 2')),
                ('btn_name2', models.CharField(max_length=40, verbose_name='Button Name 2')),
            ],
        ),
    ]
