# Generated by Django 4.2.1 on 2023-05-13 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_homecontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='homecontent',
            name='text1',
            field=models.TextField(default=1, verbose_name='Text 1'),
            preserve_default=False,
        ),
    ]
