# Generated by Django 4.2.1 on 2023-05-13 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_homecontent_text1'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-datetime',)},
        ),
        migrations.AddField(
            model_name='productcategory',
            name='classname',
            field=models.CharField(default=1, max_length=50, verbose_name='Classname'),
            preserve_default=False,
        ),
    ]
