# Generated by Django 4.2.1 on 2023-05-13 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_remove_productcategory_classname'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='to_filter',
            field=models.CharField(default=1, max_length=30, verbose_name='TO Filter'),
            preserve_default=False,
        ),
    ]
