# Generated by Django 4.2.1 on 2023-05-13 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_productcategory_to_filter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcategory',
            name='to_filter',
        ),
    ]
